#!/bin/bash

. "$(cd $(dirname $0); pwd)/common"

iso_file="$(echo $(realpath -q -e $(find ${work_dir}/out/ -name '*.iso' -print)) | tr -d '\0')"

if [[ ! -f ${iso_file} ]]; then
    _msg_error "没有生成镜像文件,无法启动虚拟机测试 ..." 1
fi

qemu-system-x86_64 \
    -smp 2 \
    -boot order=cd,menu=on,reboot-timeout=5000 \
    -m size=3072,slots=0,maxmem=$(( 3072*1024*1024 )) \
    -k en \
    -name gracefullinux,process=gracefullinux_0 \
    -drive file=${iso_file},media=cdrom,readonly=on \
    -display sdl \
    -vga virtio \
    -enable-kvm \
    -no-reboot \
    -no-shutdown \
